### ISSUE TITLE
crash server

### ISSUE THREAD

**Issue by Thecraftdu34** [thebigsmileXD/SkyBlockPE#1]
Fatal error: Cannot use pocketmine\nbt\tag\String as String because 'String' is a special class name in /home/gsp_98/srv1.hmserv.eu-19157/plugins/SkyBlockPE-master/src/thebigsmileXD/SkyBlock/subcommand/ClaimSubCommand.php on line 14

**Comment by thebigsmileXD** [comment]
Forgot to update the readme here, its inactive and won't be continued
