### ISSUE TITLE
Error: "Call to a member function close() on null" (EXCEPTION) 

### ISSUE THREAD

**Issue by victorpk1999** [thebigsmileXD/SkyBlockPE#12]
When I start my server I foud that error:

Error: "Call to a member function close() on null" (EXCEPTION) in "/phar_SkyBlockPE-master_iWOFeRsC3bS9Isl.phar/src/SkyBlock/SkyBlock" at line 461

I have Genisys(build 130, from Jenkins), based on PHP 7.0.10.
Sorry for my bad english.

**Comment by thebigsmileXD** [comment]
Hmm, maybe your binary does not have mysql

**Comment by victorpk1999** [comment]
How can i get mysql binary ?

**Comment by thebigsmileXD** [comment]
@salmon_ger can you give him the library?

**Comment by victorpk1999** [comment]
ok, thansk a lot

**Comment by Adam1609** [comment]
but still, the small line said sql is not support in this fork
Using Genisys and @SalmonGER 's Binarys

**Comment by NycuRO** [comment]
@thebigsmileXD [Server thread/CRITICAL]: Error: "Call to a member function close() on null" (EXCEPTION) in "/SkyBlockPE-master CODE/src/SkyBlock/SkyBlock" at line 461
Killed.

I have same issue

**Comment by SalmonGER** [comment]
@victorpk1999 https://github.com/SalmonGER/PocketMine-MP-Binarys

**Comment by victorpk1999** [comment]
@SalmonGER same error "sqlite not supported for skyblock in this fork"
"Call to a member function close() on null" (EXCEPTION) in "/Skyblock.phar/src/SkyBlock/SkyBlock" at line 461 with your php binnary. I have only this skyblock plugin. 



**Genisys Crash Dump Sun Sep 11 22:54:11 CEST 2016**

Error: Constant pocketmine\PATH already defined
File: /src/pocketmine/PocketMine
Line: 90
Type: E_NOTICE

Code:
[81] 
[82] 	/*
[83] 	 * Startup code. Do not look at it, it may harm you.
[84] 	 * Most of them are hacks to fix date-related bugs, or basic functions used after this
[85] 	 * This is the only non-class based file on this project.
[86] 	 * Enjoy it as much as I did writing it. I don't want to do it again.
[87] 	 */
[88] 
[89] 	if(\Phar::running(true) !== ""){
[90] 		@define('pocketmine\PATH', \Phar::running(true) . "/");
[91] 	}else{
[92] 		@define('pocketmine\PATH', \getcwd() . DIRECTORY_SEPARATOR);
[93] 	}
[94] 
[95] 	if(version_compare("7.0", PHP_VERSION) > 0){
[96] 		echo "[CRITICAL] You must use PHP >= 7.0" . PHP_EOL;
[97] 		echo "[CRITICAL] Please use the installer provided on the homepage." . PHP_EOL;
[98] 		exit(1);
[99] 	}
[100] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 0000000000000000000000000000000000000000 [Protocol 82; API 2.0.0]
uname -a: Windows NT DESKTOP-PAPB62V 10.0 build 10586 (Windows 10) AMD64
PHP version: 7.0.10
Zend version: 3.0.0
OS : WINNT, win

Server uptime: 0 seconds
Number of loaded worlds: 0
Players online: 0/20

Loaded plugins:
SkyBlock 1.0.2 by thebigsmileXD mwvent Wies and Exxarion for API(s) 2.0.0

**Comment by Adam1609** [comment]
The same :(

**Comment by thebigsmileXD** [comment]
> but still, the small line said sql is not support in this fork

It says # _**SQL**_ Not supported. Config is incorrect, closed, invalid.

**Comment by thebigsmileXD** [comment]
Fixed this error.
