### ISSUE TITLE
Known Bugs

### ISSUE THREAD

**Issue by thebigsmileXD** [thebigsmileXD/SkyBlockPE#13]
- [ ] Chests on /is claim are not centered but on the corner
- [ ] plots are way too small
- [ ] islands do not generate perfectly centered (need rewrite)
- [ ] No /is jobs or something (things you can finish and get rewards for)
- [x] Config sets sqlite by default

**Comment by Adam1609** [comment]
:( error when opened, i hate this

**Comment by thebigsmileXD** [comment]
@Adam1609 
> Config sets sqlite by default

**Comment by Adam1609** [comment]
I know, and Im trying to fix that, if i could, i will make a pull request
