### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Shadow166050** [thebigsmileXD/SkyBlockPE#17]
01.11 23:22:25 [Server] Asynchronous Worker #1 thread/CRITICAL ClassNotFoundException: "Class SkyBlockStructure not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
01.11 23:22:25 [Server] Asynchronous Worker #2 thread/CRITICAL ClassNotFoundException: "Class SkyBlockStructure not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

01.11 23:22:25 [Server] Server thread/CRITICAL Could not execute asynchronous task PopulationTask: Task crashed

**Comment by thebigsmileXD** [comment]
Quote from the readme: "Please note that this is still in development."

And the code is ol, i have local changes. The structures generate, but don't fully generate (only parts, on chunk borders it will fail)
