### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by caspervanneck** [thebigsmileXD/SkyBlockPE#19]
@thebigsmileXD  fix it i have a mysql now

**Comment by caspervanneck** [comment]
and cant claim i tink

**Comment by thebigsmileXD** [comment]
Intelligable

**Comment by thebigsmileXD** [comment]
is auto doesnt work yet, but wth do you mean

**Comment by caspervanneck** [comment]
if you generate a skyblock world no plots

**Comment by caspervanneck** [comment]
@thebigsmileXD

**Comment by thebigsmileXD** [comment]
lol? it works for me

**Comment by caspervanneck** [comment]
for my now to but i get this bin\php\php.exe: Segmentation fault

**Comment by caspervanneck** [comment]
if i try to claim

**Comment by thebigsmileXD** [comment]
segfault confirmed.
