### ISSUE TITLE
Damm this is Nice but cant use help me 

### ISSUE THREAD

**Issue by TheMinionBeast** [thebigsmileXD/SkyBlockPE#2]
# **_DAMMMM_**

Hello i installed the plug-in in my server but it Will crash hope you can fix d because the only SKYBLOCK plug-in for Pe is owned by u :-)

**Comment by TheMinionBeast** [comment]
👍

**Comment by thebigsmileXD** [comment]
-> readme: project not supported anymore

**Comment by thebigsmileXD** [comment]
Also its not the only plugin. There are others, but not in island shape, these are in the old "L" shape

**Comment by TheMinionBeast** [comment]
Wich one?

**Comment by TheMinionBeast** [comment]
And Youre Great  developer Thumps Up!!!!

**Comment by thebigsmileXD** [comment]
:D okay, try now! Actually had time and was in the mood to update it!

**Comment by TheMinionBeast** [comment]
Thanks, and btw, is iT possible to load in zip? Ziploadder crahed

**Comment by thebigsmileXD** [comment]
No idea
