### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by BlawoHD** [thebigsmileXD/SkyBlockPE#20]
Ich kriege zuerst das:
Warning: mysqli::__construct(): (HY000/2002): Connection refused in /Users/BlawoHD/Desktop/Plugin/Genisys-master/plugins/SkyBlockPE-master/src/SkyBlock/provider/MYSQLDataProvider.php on line 21

Warning: mysqli::query(): Couldn't fetch mysqli in /Users/BlawoHD/Desktop/Plugin/Genisys-master/plugins/SkyBlockPE-master/src/SkyBlock/provider/MYSQLDataProvider.php on line 30

Warning: mysqli::prepare(): Couldn't fetch mysqli in /Users/BlawoHD/Desktop/Plugin/Genisys-master/plugins/SkyBlockPE-master/src/SkyBlock/provider/MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in /Users/BlawoHD/Desktop/Plugin/Genisys-master/plugins/SkyBlockPE-master/src/SkyBlock/provider/MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in /Users/BlawoHD/Desktop/Plugin/Genisys-master/plugins/SkyBlockPE-master/src/SkyBlock/provider/MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in /Users/BlawoHD/Desktop/Plugin/Genisys-master/plugins/SkyBlockPE-master/src/SkyBlock/provider/MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in /Users/BlawoHD/Desktop/Plugin/Genisys-master/plugins/SkyBlockPE-master/src/SkyBlock/provider/MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in /Users/BlawoHD/Desktop/Plugin/Genisys-master/plugins/SkyBlockPE-master/src/SkyBlock/provider/MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in /Users/BlawoHD/Desktop/Plugin/Genisys-master/plugins/SkyBlockPE-master/src/SkyBlock/provider/MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in /Users/BlawoHD/Desktop/Plugin/Genisys-master/plugins/SkyBlockPE-master/src/SkyBlock/provider/MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in /Users/BlawoHD/Desktop/Plugin/Genisys-master/plugins/SkyBlockPE-master/src/SkyBlock/provider/MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in /Users/BlawoHD/Desktop/Plugin/Genisys-master/plugins/SkyBlockPE-master/src/SkyBlock/provider/MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in /Users/BlawoHD/Desktop/Plugin/Genisys-master/plugins/SkyBlockPE-master/src/SkyBlock/provider/MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in /Users/BlawoHD/Desktop/Plugin/Genisys-master/plugins/SkyBlockPE-master/src/SkyBlock/provider/MYSQLDataProvider.php on line 148

Danach das:

"Das Event 'pocketmine\event\player\PlayerMoveEvent' konnte nicht an 'SkyBlock v1.0.2' weitergegeben werden: Call to a member function bind_param() on null in SkyBlock\EventListener"

**Comment by caspervanneck** [comment]
you must make a database zo stop spaming

**Comment by thebigsmileXD** [comment]
-> Connection Refused °-°

Es sagt doch schon was los ist. Check mal deine config, passwort oder user falsch

**Comment by BlawoHD** [comment]
Kannst du es auch ohne machen? Also ohne MYSQL? @thebigsmileXD

**Comment by thebigsmileXD** [comment]
Nein, es ist absichtlich ein mysql fork
