### ISSUE TITLE
Auto command doesn't work

### ISSUE THREAD

**Issue by Xelcronia** [thebigsmileXD/SkyBlockPE#21]
When i do ```/is auto``` , it says "No free plot found in this world".  Is there any alternate way for a player to claim a plot?

**Comment by thebigsmileXD** [comment]
Yes. is auto only teleport you anyways. is claim -> claim the island you stand on

Alternative for it would be  flying/tp to an island and then claim

**Comment by Xelcronia** [comment]
I don't think i can use it for production environment?

**Comment by thebigsmileXD** [comment]
Correctly. As far as i remember this even stands really big in the readme, if not i'll add it

**Comment by Xelcronia** [comment]
Yeh. I saw that its still in development.
