### ISSUE TITLE
Help me :((

### ISSUE THREAD

**Issue by huybinh2009** [thebigsmileXD/SkyBlockPE#24]
Warning: mysqli::__construct(): (HY000/2002): No connection could be made because the target machine actively refused it.
 in C:\Users\Administrator\Documents\administrator\Desktop\SkyBlock\plugins\SkyBlock\src\SkyBlock\provider\MYSQLDataProvider.php on line 21

Warning: mysqli::query(): Couldn't fetch mysqli in C:\Users\Administrator\Documents\administrator\Desktop\SkyBlock\plugins\SkyBlock\src\SkyBlock\provider\MYSQLDataProvider.php on line 30

Warning: mysqli::prepare(): Couldn't fetch mysqli in C:\Users\Administrator\Documents\administrator\Desktop\SkyBlock\plugins\SkyBlock\src\SkyBlock\provider\MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in C:\Users\Administrator\Documents\administrator\Desktop\SkyBlock\plugins\SkyBlock\src\SkyBlock\provider\MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in C:\Users\Administrator\Documents\administrator\Desktop\SkyBlock\plugins\SkyBlock\src\SkyBlock\provider\MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in C:\Users\Administrator\Documents\administrator\Desktop\SkyBlock\plugins\SkyBlock\src\SkyBlock\provider\MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in C:\Users\Administrator\Documents\administrator\Desktop\SkyBlock\plugins\SkyBlock\src\SkyBlock\provider\MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in C:\Users\Administrator\Documents\administrator\Desktop\SkyBlock\plugins\SkyBlock\src\SkyBlock\provider\MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in C:\Users\Administrator\Documents\administrator\Desktop\SkyBlock\plugins\SkyBlock\src\SkyBlock\provider\MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in C:\Users\Administrator\Documents\administrator\Desktop\SkyBlock\plugins\SkyBlock\src\SkyBlock\provider\MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in C:\Users\Administrator\Documents\administrator\Desktop\SkyBlock\plugins\SkyBlock\src\SkyBlock\provider\MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in C:\Users\Administrator\Documents\administrator\Desktop\SkyBlock\plugins\SkyBlock\src\SkyBlock\provider\MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in C:\Users\Administrator\Documents\administrator\Desktop\SkyBlock\plugins\SkyBlock\src\SkyBlock\provider\MYSQLDataProvider.php on line 148

Warning: mysqli::prepare(): Couldn't fetch mysqli in C:\Users\Administrator\Documents\administrator\Desktop\SkyBlock\plugins\SkyBlock\src\SkyBlock\provider\MYSQLDataProvider.php on line 148
[Tesseract] [19:42:45] INFO> Preparing level "world"
[Tesseract] [19:42:45] INFO> Preparing level "nether"
[Tesseract] [19:42:45] INFO> Starting GS4 status listener
[Tesseract] [19:42:45] INFO> Query running on 0.0.0.0:19132
[Tesseract] [19:42:45] INFO> Default game type: Survival Mode
[Tesseract] [19:42:45] INFO> Done (3.853s)! For help, type "help" or "?"

**Comment by huybinh2009** [comment]
How to fix

**Comment by thebigsmileXD** [comment]
BY READING THE README.

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/24259587/9dd95328-0ff1-11e7-8d85-d4905cf92157.png)
![image](https://cloud.githubusercontent.com/assets/8733998/24259594/a3820db0-0ff1-11e7-9ecc-9f4edb7ac08b.png)
Y U NO READ.

**Comment by huybinh2009** [comment]
thank
