### ISSUE TITLE
idiot

### ISSUE THREAD

**Issue by bogdanboruzs** [thebigsmileXD/SkyBlockPE#26]
So whats the point to made this fucking plugin when you not fucking helping to others omg!!!!!!

**Comment by Skull3x** [comment]
what?

**Comment by caspervanneck** [comment]
@bogdanboruzs ssst this plugin is dead

**Comment by thebigsmileXD** [comment]
Stop, Hammertime.

**Comment by thebigsmileXD** [comment]
Whats the point in answering idiots that can't read a R E A D - M E

**Comment by thebigsmileXD** [comment]
Adrian Higgs, [03.04.17 10:22]
Not sure what language thats in

Adrian Higgs, [03.04.17 10:23]
Tell that kid to go back to school
