### ISSUE TITLE
Generator problems

### ISSUE THREAD

**Issue by NemanjaMAX** [thebigsmileXD/SkyBlockPE#29]
Error: "Call to undefined method pocketmine\level\generator\normal\biome\PlainBiome::getColor()" (EXCEPTION) in "/plugins/SkyBlockPE-master/src/SkyBlock/SkyBlockGenerator" at line 105

CRITICAL> Could not execute asynchronous task PopulationTask: Task crashed

**Comment by NemanjaMAX** [comment]
I cannot tp to world

**Comment by caspervanneck** [comment]
its dead you shuld a other plugin

**Comment by caspervanneck** [comment]
@NemanjaMAX

**Comment by thebigsmileXD** [comment]
Like every other fucking issue.. Outdated plugin, unmaintained. Removing issue tracker or repo later
