### ISSUE TITLE
Teleport issues

### ISSUE THREAD

**Issue by Skull3x** [thebigsmileXD/SkyBlockPE#3]
Player get's teleported outside the skyblock island and falls to they're death

**Comment by thebigsmileXD** [comment]
I have no idea right now how to fix it. The protections are also wrong

**Comment by Callum9966** [comment]
I just use /sethome Skyblock and /home Skyblock instead of /is home

**Comment by Moonneko** [comment]
i fixxed skyblock plugins, it is working well in my server . sb.fcavn.net:19132

**Comment by Callum9966** [comment]
Can I have a copy of that?

**Comment by thebigsmileXD** [comment]
@Moonneko Based of my plugin? May you create a PR

**Comment by Callum9966** [comment]
What's a PR? :/

**Comment by thebigsmileXD** [comment]
http://lmgtfy.com/?q=What%27s+a+PR+GitHub

**Comment by Moonneko** [comment]
No i base of myplot plugins, i cant PR . Sorry my bad english

**Comment by thebigsmileXD** [comment]
Well, mine is also based of myplots ..

**Comment by Adam1609** [comment]
Well it is a teleport issue.....

**Comment by thebigsmileXD** [comment]
Well, the generator is "totally" rewritten now, plot sizes should work too. For now i still place borders around plots because.. lets say it like this: plots are offset lol.. they are not always exactly in the center. I would need help with that because instead of fixed chunk coordinates they are now dynamic..

**Comment by thebigsmileXD** [comment]
And p home + p auto teleport correctly

**Comment by thebigsmileXD** [comment]
Create a new issue if you experience another problem
