### ISSUE TITLE
Generator error

### ISSUE THREAD

**Issue by XDqrkneZ** [thebigsmileXD/SkyBlockPE#30]
I get this error when I go to the SkyBlock world

I am using Tesseract

 06.05 12:24:34 [Server] CRITICAL Could not execute asynchronous task PopulationTask: Task crashed
06.05 12:24:34 [Server] CRITICAL Error: "Call to undefined method pocketmine\level\generator\normal\biome\PlainBiome::getColor()" (EXCEPTION) in "/phar_SkyBlockPE-master_5PlTRUzaUQUbNWE.phar/src/SkyBlock/SkyBlockGenerator" at line 105

**Comment by thebigsmileXD** [comment]
What are you all. Fucking stupid?

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/25779381/ba5c2b5e-3316-11e7-9321-32d79ca742d3.png)

**Comment by XDqrkneZ** [comment]
delete the repo LOL

**Comment by thebigsmileXD** [comment]
Alright
