### ISSUE TITLE
Something about DynmapPE (didn't know where to post it)

### ISSUE THREAD

**Issue by Sandertv** [thebigsmileXD/SkyBlockPE#4]
Hey!
So you told me you needed the plugin Volt to complete the dynmap plugin for pocketmine, and that it doesn't work. (or something in that direction :P) So I was just looking through github and thought you could maybe use this plugin: https://github.com/Ad5001/Online

**Comment by thebigsmileXD** [comment]
Yea, already checked out "Online", i may concider implementing this, but first of all i have to find a more efficient way to display the website

**Comment by Thunder33345** [comment]
i would prefer a client(the one that is displaying the map) server(the PM server itself) setup since not all host have port 80 open

**Comment by thebigsmileXD** [comment]
What do you mean

**Comment by Thunder33345** [comment]
meaning the map should be hosted off site
ex
map.server.net will be where to view the map(linked by using APIs) and
play.server.net will be where players join

to re-clarify what i mean:
i suggest that the map view generator should be off side and not build on the PM instance

**Comment by thebigsmileXD** [comment]
=== same domain. you would have to change this on your hostserver

**Comment by thebigsmileXD** [comment]
i suggest that the map view generator should be off side and not build on the PM instance

**Comment by Thunder33345** [comment]
hmm OR just focus on the project itself first and implement the off side setup in latter days when we actually have a thing to base off

well or try POST the required date to the client(the one that will display the map) and the client will compute the map therefore it wont give too much stress on the PM instance itself

**Comment by thebigsmileXD** [comment]
Dynmap will be re-done, it will now read the leveldata directly instead of using arrays

**Comment by Sandertv** [comment]
Would be amazing.

**Comment by thebigsmileXD** [comment]
Found the data again! hoo-ray!
https://github.com/thebigsmileXD/DynMapPE
