### ISSUE TITLE
Distance between islands

### ISSUE THREAD

**Issue by localhostmaster** [thebigsmileXD/SkyBlockPE#5]
How to generate more distance between islands??

**Comment by thebigsmileXD** [comment]
It will bug with the plot protection. But look int the settings plot size

**Comment by localhostmaster** [comment]
Where is settings plot size?

**Comment by thebigsmileXD** [comment]
https://github.com/thebigsmileXD/SkyBlockPE/blob/master/resources/config.yml#L20-L21

It even stands there.
