### ISSUE TITLE
Water and Lava don't move

### ISSUE THREAD

**Issue by Adam1609** [thebigsmileXD/SkyBlockPE#6]
Still this error now! Can you please fix?

**Comment by thebigsmileXD** [comment]
uhm well maybe after a recode or something. i found a fix for this in MyPlot.

**Comment by Adam1609** [comment]
Could you fix it. And when generate a world it has only like 2 islands or something.

**Comment by thebigsmileXD** [comment]
Then your server is laggy. or increase the view distance in the settings of your server
